language: node_js
notifications:
  email: false
node_js:
  - '9'
  - '8'
before_script:
  - yarn
script:
  - yarn test
  - yarn check-coverage
  - yarn build
after_success:
  - yarn report-coverage
branches:
  only:
    - next
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
