language: node_js
notifications:
  email: true
node_js:
  - '9'
  - '8'
before_script:
  - yarn install
  - mkdir .nyc_output
  - chmod go+w .nyc_output
script:
  - yarn test
  - yarn check-coverage
before_build:
  - yarn global add typedoc
build:
  - yarn build
branches:
  only:
    - develop
    - master
  except:
    - /^v\d+\.\d+\.\d+$/
